[package]
name = "leben-compiler"
version = "0.1.0"
edition = "2024"

[dependencies]
leben-parsable = { path = "leben-parsable" }
ron = "0.11.0"
serde = { version = "1.0.228", features = ["derive"] }
